language: node_js

sudo: false

env:
  global:
    - TEST_COMMAND="yarn test"
    - COVERAGE=false

matrix:
  fast_finish: true
  include:
  - node_js: 7
    env: TEST_COMMAND="yarn test:cov" COVERAGE=true
  - node_js: 6
  - node_js: "stable"

deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    skip_cleanup: true

cache:
  yarn: true
  directories:
    - node_modules

script:
  - $TEST_COMMAND

after_success:
  - if [[ "$COVERAGE" = true ]]; then yarn add coveralls@2 && yarn coverage:upload; fi